asr_sherpa_onnx:
  model_path: /home/kaiser/下载/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/model.onnx
  use_itn: true        # 逆文本归一化
  language: "auto"
  tokens: /home/kaiser/下载/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/tokens.txt
  num_threads: 1
  
  # 在线识别模型配置（如果使用支持在线识别的模型）
  # online_model:
  #   transducer:
  #     encoder: ""
  #     decoder: ""
  #     joiner: ""
  #   paraformer: ""
  #   tokens: ""
  #   num_threads: 1
  #   decoding_method: "greedy_search"


#webscocket server
websocket:
  port: 8000
  log_level : INFO
  max_connections: 3
  connection_timeout: 300